### ISSUE TITLE
do you have data with categorical values?

### ISSUE THREAD

**Issue by Sandy4321** [SamsungSAILMontreal/ForestDiffusion#3]
do you have data with categorical values? 
I can not find data with categorical data 

from data_loaders import dataset_loader
import pickle
if __name__ == "__main__":

    datasets=['iris', 'wine', 'california', 'parkinsons', 'climate_model_crashes', 'concrete_compression', 'yacht_hydrodynamics', 'airfoil_self_noise', 'connectionist_bench_sonar', 'ionosphere', 'qsar_biodegradation', 'seeds', 'glass', 'ecoli', 'yeast', 'libras', 'planning_relax', 'blood_transfusion', 'breast_cancer_diagnostic', 'connectionist_bench_vowel', 'concrete_slump', 'wine_quality_red', 'wine_quality_white', 'bean']

    for dataset in datasets:
        print(dataset)

        X, bin_x, cat_x, int_x, y, bin_y, cat_y, int_y = dataset_loader(dataset)
        print(len(X))
        print(len(X[0]))
        print('cat_x', cat_x)
        print('bin_x', bin_x)
        with open(dataset + '.pickle', 'wb') as handle:
            pickle.dump([X, bin_x, cat_x, int_x, y, bin_y, cat_y, int_y], handle ) #, protocol=pickle.HIGHEST_PROTOCOL)        
        q = 0
    q = 0

output
iris
150
4
cat_x None
bin_x None
wine
178
13
cat_x None
bin_x None
california
20640
8
cat_x None
bin_x None
parkinsons
195
22
cat_x None
bin_x None
climate_model_crashes
540
18
cat_x None
bin_x None
concrete_compression
1030
8
cat_x None
bin_x None
yacht_hydrodynamics
308
6
cat_x None
bin_x None
airfoil_self_noise
1503
5
cat_x None
bin_x None
connectionist_bench_sonar
208
60
cat_x None
bin_x None
ionosphere
351
33
cat_x None
bin_x [0]
qsar_biodegradation
1055
41
cat_x None
bin_x [23, 24, 28]
seeds
210
7
cat_x None
bin_x None
glass
214
9
cat_x None
bin_x None
ecoli
336
7
cat_x None
bin_x None
yeast
1484
8
cat_x None
bin_x None
libras
360
90
cat_x None
bin_x None
planning_relax
182
12
cat_x None
bin_x None
blood_transfusion
748
4
cat_x None
bin_x None
breast_cancer_diagnostic
569
30
cat_x None
bin_x None
connectionist_bench_vowel
990
10
cat_x None
bin_x None
concrete_slump
103
7
cat_x None
bin_x None
wine_quality_red
1599
10
cat_x None
bin_x None
wine_quality_white
4898
11
cat_x None
bin_x None
bean
13611
16
cat_x None
bin_x None

**Comment by Sandy4321** [comment]
check cat_x,
it is what i show you, all cat_x is None

**Comment by AlexiaJM** [comment]
cat_x, bin_x, bin_y, cat_y are all categorical variables (>=2 categories), there is no cat_x in the 24 datasets (taken from https://arxiv.org/abs/2002.03860), but there are bin_x, bin_y, cat_y. Btw, the bin vs cat distinction is not important, they are effectively all dummy-coded and rounded after in ForestDiffusion.

**Comment by Sandy4321** [comment]
Btw, the bin vs cat distinction is not important, they are effectively all dummy-coded and rounded after in ForestDiffusion.

no exactly 
my guess , you just can not find data with categorical features ?

**Comment by Pierre-Bartet** [comment]
Up. This is a pretty legit question: not only there are no `cat_x`, but also in the default parameters forest diffusion build different models for `cat_y` and `bin_y` (see [here](https://github.com/SamsungSAILMontreal/ForestDiffusion/blob/2a8bd36d334dbad06c10db2d9f0c016baaf509e3/script_generation.py#L388C1-L388C19)) .
In the end the paper is still awesome but it is hard to know how well forest diffusion works for categorical data or for categorical + continuous combinations. Who knows it might even turn out that it works fine even with tens of categorical features!

**Comment by AlexiaJM** [comment]
I'm already adding a few categorical datasets filled with cat_x or bin_x. They will be incorporated soon. The approach works well with categorical data. It was just annoying because some of the other methods had bugs with only-categorical-data, so I had to make it sure it works for every method. It's rerunning every scenario with every method and making sure that there is not one method that has bug that makes it more difficult to manage. 

Yes, there are fewer categorical datasets on UCI than numerical datasets and the set of datasets for which this code is based on (https://arxiv.org/abs/2002.03860) has few categorical variables, although it has some.

Btw, the reason why it process cat_x and bin_x differently is because cat_x were previously one-hot encoded, but I switched to dummy-coding at some point during development because its more efficient (one less variable). The thing is that with dummy-coding, a binary variable is exactly equal to its dummy-coding, and since the dummy-coding function will make it 0 or 1 based on if its higher than 0.5, this means that treating it as a cat_x or bin_x is exactly the same. So, it does not matter anymore whether you set them to bin_x or cat_x; if there is any difference, it will be random seed variations.

**Comment by Pierre-Bartet** [comment]
Thanks!

**Comment by Sandy4321** [comment]
1
cool, looking forward to try categorical datasets
2
Yes, there are fewer categorical datasets on UCI than numerical datasets
try to use kaggle data sets?

**Comment by Sandy4321** [comment]
1
fyi
https://mltechniques.com/2023/09/19/new-python-library-to-evaluate-ai-generated-data-and-compare-models/
2
Yes, there are fewer categorical datasets on UCI than numerical datasets
you can try kaggle daya sets ?
