### ISSUE TITLE
Measures of feature importance

### ISSUE THREAD

**Issue by jamesruffle** [SamsungSAILMontreal/ForestDiffusion#5]
Dear ForestDiffusion team,

We are interested in using your code in our research. Do you have any experience or recommendations for deriving measures of feature importance (e.g. [SHAP](https://shap.readthedocs.io/en/latest/)) with your model?

James

**Comment by AlexiaJM** [comment]
Hi James,

Thanks for the interest! It would be quite interesting to visualize the feature importance of these models. We have not looked at it yet. I just made a simple example with SHAP, showing how to extract the XGBoost models and use them to get the feature importance, see: https://colab.research.google.com/drive/1hhizV0zYSIhWKyiycAll7XWsOXjAc2qx?usp=sharing. 

Just keep in mind that there are k*n_t*d models (k is the number of classes if label_y is provided, otherwise k=1; d is the number of variables, n_t is the number of noise levels), which each have their feature importance and the input must be the noisy data x(t) at a specific noise level t. So looking at this may be tricky.

Alexia
